global:
  clusterName: kubeaid-demo-azure
  kubernetes:
    version: v1.31.1
  kubeaid:
    repo: https://github.com/Archisman-Mridha/kubeaid
  kubeaidConfig:
    repo: https://github.com/Archisman-Mridha/kubeaid-config
  additionalUsers: 
    - name: archi
      sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCMB0BJ1vL53/xiDCfswJWOrBYc39MbnmMnAK9ATohDqgT1ZrvLODbw5T1NTOLsVyuWNXMB9HfPPXg3Qm5L5UXoIj5JeyIY1ArUxjdW5LI4fsYgYHfRSv3gSZFpuJj12+myBxdoNYCDNDrzYF5T3D2is0lqcSG+3UerkY7ox8WuHMSO69bUAn72ugw01TgycdXpX5jvGLb84yl2Xct1/YFsh9UKhVYWx8qdz5r7FM4h5KDIIi2yjAEjwm4DfYKT/9dlzTodzeim4Z755AGXpFWjlQYaV8vNLHhIkDEtDOZTDtePFwQ64cw1e8cYzuRqDRxCVA9mWQtWwbMgklAv5h0ZTu8cJ9XcomQV9W2NCieBJyu+bj71AKFg3qTD9aMBq2zBXshoZwvmPlrIfAreALPEcPQvn6T8vHGvfk6Pf91B7I1Tu9ds0X0Vp5KELR6wwZQx2JKwMJillzC4Z3GY4/oi5J5C6WnlB3TxCvsivBo3TtEc3phylnfHNvRbwCqch2k= robot-webservice-app-user
provider:
  azure: true

azure:
  tenantID: 044f8a56-5941-491f-9618-310d92b5a3dd
  subscriptionID: c4508db5-f783-4ac1-9221-1116c3a6db47
  location: northcentralus
  resourceGroup: kubeaid-demo-azure

  sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCMB0BJ1vL53/xiDCfswJWOrBYc39MbnmMnAK9ATohDqgT1ZrvLODbw5T1NTOLsVyuWNXMB9HfPPXg3Qm5L5UXoIj5JeyIY1ArUxjdW5LI4fsYgYHfRSv3gSZFpuJj12+myBxdoNYCDNDrzYF5T3D2is0lqcSG+3UerkY7ox8WuHMSO69bUAn72ugw01TgycdXpX5jvGLb84yl2Xct1/YFsh9UKhVYWx8qdz5r7FM4h5KDIIi2yjAEjwm4DfYKT/9dlzTodzeim4Z755AGXpFWjlQYaV8vNLHhIkDEtDOZTDtePFwQ64cw1e8cYzuRqDRxCVA9mWQtWwbMgklAv5h0ZTu8cJ9XcomQV9W2NCieBJyu+bj71AKFg3qTD9aMBq2zBXshoZwvmPlrIfAreALPEcPQvn6T8vHGvfk6Pf91B7I1Tu9ds0X0Vp5KELR6wwZQx2JKwMJillzC4Z3GY4/oi5J5C6WnlB3TxCvsivBo3TtEc3phylnfHNvRbwCqch2k= robot-webservice-app-user

  userAssignedIdentity:
    name: cluster-api
    clientID: 150ede7e-60d4-4fff-9984-ad82e7f860ae

  serviceAccountIssuer:
    url: https://kubeaiddemo.blob.core.windows.net/oidc-provider

  

  controlPlane: 
    loadBalancerType: Public
    diskSizeGB: 128
    vmSize: Standard_D2ps_v6
    replicas: 1

  nodeGroups: 
    - name: primary
      cpu: 2
      memory: 8
      minSize: 1
      maxSize: 3
      labels:
        node-role.kubernetes.io/bootstrapper: ""
        node.cluster.x-k8s.io/nodegroup: bootstrapper
      taints: []
      vmSize: Standard_D2ps_v6
      diskSizeGB: 128
