apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: azure-workload-identity-webhook
  namespace: argocd
spec:
  destination:
    namespace: azure-workload-identity-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/Archisman-Mridha/kubeaid
      path: argocd-helm-charts/azure-workload-identity-webhook
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-azure/argocd-apps/values-azure-workload-identity-webhook.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  project: kubeaid
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true

