apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: ccm-hcloud
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Archisman-Mridha/kubeaid
      path: argocd-helm-charts/ccm-hcloud
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-hcloud/argocd-apps/values-ccm-hcloud.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
