apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    labels:
      kubeaid.io/version: "10.0.0"
      kubeaid.io/managed-by: "kubeaid"
      kubeaid.io/priority: "default"
  name: ccm-aws
  namespace: argo-cd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: kubeaid
  sources:
    - repoURL: https://github.com/Archisman-Mridha/kubeaid
      path: argocd-helm-charts/ccm-aws
      targetRevision: 10.0.0
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-aws/argocd-apps/ccm-aws.values.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
