apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    kubeaid.io/version: "HEAD"
    kubeaid.io/managed-by: "kubeaid"
    kubeaid.io/priority: "default"
  name: velero
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: velero
  project: kubeaid
  sources:
    - repoURL: https://github.com/Archisman-Mridha/kubeaid
      path: argocd-helm-charts/velero
      targetRevision: HEAD
      helm:
        valueFiles:
          - $values/k8s/kubeaid-demo-azure/argocd-apps/values-velero.yaml
    - repoURL: https://github.com/Archisman-Mridha/kubeaid-config
      targetRevision: HEAD
      ref: values
  syncPolicy:
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - CreateNamespace=true
